server.port=8085
spring.application.name=order-fulfilment-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/orderfulfilmentdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:showdown}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:showdown123}
spring.jpa.hibernate.ddl-auto=none
management.endpoints.web.exposure.include=health,info
