server.port=8085
spring.application.name=order-fulfilment-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/orderfulfilmentdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:showdown}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:showdown123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
management.endpoints.web.exposure.include=health,info
