# MicroProfile Config -- catalog-service
app.name=catalog-service
app.version=1.0.0-SNAPSHOT
db.url=${DB_URL:jdbc:postgresql://localhost:5442/catalogdb}
db.user=${DB_USER:showdown}
db.password=${DB_PASSWORD:showdown123}

##########################################
# MicroProfile JWT / Keycloak
##########################################

mp.jwt.verify.issuer=http://keycloak:8080/realms/jpetstore
mp.jwt.verify.publickey.location=http://keycloak:8080/realms/jpetstore/protocol/openid-connect/certs