server.port=8082
spring.application.name=catalog-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalogdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:showdown}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:showdown123}
spring.jpa.hibernate.ddl-auto=none
management.endpoints.web.exposure.include=health,info
