# MicroProfile Config -- order-capture-service
app.name=order-capture-service
app.version=1.0.0-SNAPSHOT
db.url=${DB_URL:jdbc:postgresql://localhost:5444/ordercapturedb}
db.user=${DB_USER:showdown}
db.password=${DB_PASSWORD:showdown123}
inventory-service/mp-rest/url=http://wf-inventory-service:8080/inventory-service
user-service/mp-rest/url=http://wf-user-service:8080/user-service

