app.name=cart-service
app.version=1.0.0-SNAPSHOT

redis.host=wf-cart-db-master
redis.port=6379


redis.sentinel.hosts=
redis.master.name=mymaster

##########################################
# MicroProfile JWT / Keycloak
##########################################

mp.jwt.verify.issuer=http://keycloak:8080/realms/jpetstore
mp.jwt.verify.publickey.location=http://keycloak:8080/realms/jpetstore/protocol/openid-connect/certs

smallrye.jwt.path.groups=realm_access/roles
